/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memorylog;

import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bao Luu
 */
public class QuizRun extends javax.swing.JFrame {
  static QuizTester qt;
  SubjectTester st = new SubjectTester();
  ArrayList<DateQuestion> questions = new ArrayList<DateQuestion>();
  public static int count;
  /**
   * Creates new form QuizRun
   */
  public QuizRun() {
    initComponents();
    setSize(800,600);
    //qt = new QuizTester();
    st.load();
    questions = st.run();
    jLabel2.setText(qt.getQuestions().get(qt.getNumber()));
    jLabel4.setText(qt.getQuestions().size() + " Questions"); // dung hang thu nhat so cau hoi
     
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel1.setText("Answer:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(380, 180, 90, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(380, 80, 290, 90);

        jButton1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(580, 390, 90, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jPanel2.add(jTextArea2);
        jTextArea2.setBounds(380, 230, 290, 130);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 360, 490);

        jLabel4.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel4.setText("Question");
        jLabel4.setMaximumSize(new java.awt.Dimension(87, 26));
        jLabel4.setMinimumSize(new java.awt.Dimension(87, 26));
        jLabel4.setPreferredSize(new java.awt.Dimension(87, 26));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(380, 30, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String input = "";
        input = jTextArea2.getText();
        qt.compare(input, qt.getAnswers().get(0));
        count = qt.getNumber();
      try {
          qt.saveR(1);
      } catch (IOException ex) {
          Logger.getLogger(QuizRun.class.getName()).log(Level.SEVERE, null, ex);
      }
        this.setVisible(false);
        new QuizConts().setVisible(true); // Main Form to show after the Login Form..
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(QuizRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(QuizRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(QuizRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(QuizRun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        
        new QuizRun().setVisible(true);
        
      }
      
    });
    
  }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
