/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memorylog;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bao Luu
 */
public class QuizConts extends javax.swing.JFrame {
     static QuizTester qt;
     /**
     * Creates new form QuizConts
     */
    public QuizConts() {
        qt = new QuizTester();
        if (qt.getOnly()!=8){
            initComponents();
            setSize(800,600);
        qt.load();
        jTextArea1.setText(qt.getQuestions().get(0));
        jTextField1.setText(qt.getQuestions().size() + " Questions"); // dung hang thu nhat so cau hoi
        }
        else{
            initComponents();
            setSize(800,600);
        String path = "questionAns.txt";
         try {
             qt.check(path);
         } catch (FileNotFoundException ex) {
             Logger.getLogger(QuizConts.class.getName()).log(Level.SEVERE, null, ex);
         }}
        if (qt.getNumber()==0){
        }
        else{
            qt.loadR();
            jTextArea1.setText(qt.getQuestions().get(0));
            jTextField1.setText(qt.getQuestions().size() + " Questions"); // dung hang thu nhat so cau hoi
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        setIconImages(null);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(370, 30, 120, 30);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 70, 350, 116);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(370, 230, 350, 90);

        jButton1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(620, 340, 100, 50);

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        jLabel1.setText("  Answer:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 200, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bao Luu\\Downloads\\pokemon_PNG27.png")); // NOI18N
        jLabel2.setInheritsPopupMenu(false);
        jLabel2.setMaximumSize(new java.awt.Dimension(600, 600));
        jLabel2.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 50, 646, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String input = "";
        input = jTextArea2.getText();
        qt.compare(input,qt.getAnswers().get(0));
        //count = qt.getNumber();
         try {
          qt.saveR(1);
      } catch (IOException ex) {
          Logger.getLogger(QuizRun.class.getName()).log(Level.SEVERE, null, ex);
      }
         if(qt.getNumber() != 1){
            //System.out.println("heo ");
            this.setVisible(false);
            new QuizConts().setVisible(true) ; // Main Form to show after the Login Form..
         }
         else{
            this.dispose();
            new Result().setVisible(true) ; // Main Form to show after the Login Form..   
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizConts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizConts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizConts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizConts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizConts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
